/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controlleur;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Compte;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import static org.omg.CORBA.ORB.init;

/**
 *
 * @author ASUS STRIX GAMING
 */
public class JframeHome extends javax.swing.JFrame {
    Controlleur controlleur = new Controlleur();
    String quelMenu;
    
    

    /**
     * Creates new form JframeHome
     */
    public JframeHome(String type) {
        initComponents();
        
        if(type.equalsIgnoreCase("Utilisateur")){
            menuAdmin.setVisible(false);
            MenuUser.setVisible(false);
            MenuItemCreerCompte.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        MenuItemCreerAdmin = new javax.swing.JMenuItem();
        MenuItemListeAdmin = new javax.swing.JMenuItem();
        MenuUser = new javax.swing.JMenu();
        MenuItemCreerUser = new javax.swing.JMenuItem();
        MenuItemListeUser = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItemCreerCompte = new javax.swing.JMenuItem();
        MenuItemListeCompte = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuAdmin.setText("Admin");

        MenuItemCreerAdmin.setText("Creer");
        MenuItemCreerAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerAdminActionPerformed(evt);
            }
        });
        menuAdmin.add(MenuItemCreerAdmin);

        MenuItemListeAdmin.setText("Liste");
        MenuItemListeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeAdminActionPerformed(evt);
            }
        });
        menuAdmin.add(MenuItemListeAdmin);

        jMenuBar1.add(menuAdmin);

        MenuUser.setText("User");

        MenuItemCreerUser.setText("Creer");
        MenuItemCreerUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerUserActionPerformed(evt);
            }
        });
        MenuUser.add(MenuItemCreerUser);

        MenuItemListeUser.setText("Liste");
        MenuItemListeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeUserActionPerformed(evt);
            }
        });
        MenuUser.add(MenuItemListeUser);

        jMenuBar1.add(MenuUser);

        jMenu4.setText("Compte");

        MenuItemCreerCompte.setText("Creer");
        MenuItemCreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerCompteActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItemCreerCompte);

        MenuItemListeCompte.setText("Liste");
        MenuItemListeCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListeCompteActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItemListeCompte);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("  A propos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("  Aide");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemListeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeAdminActionPerformed
        quelMenu = "admin";
        try {
            // TODO add your handling code here:
            List<Admin> listAdmin = controlleur.routeVersListAllAdmin();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Login");
            for (Admin ad : listAdmin)
                model.addRow(new String[]{ad.getIdadmin()+"",ad.getNom(),ad.getLogin()}); 
                table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JframeHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MenuItemListeAdminActionPerformed

    private void MenuItemListeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeUserActionPerformed
        quelMenu = "User";
        try {
            // TODO add your handling code here:
            List<Utilisateur> listUtilisateur = controlleur.routeVersListAllUtilisateur();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Login");
            model.addColumn("Password");
            model.addColumn("Nom");
            model.addColumn("Prenom");
            model.addColumn("Date de naissance");
            model.addColumn("Genre");
            model.addColumn("IdAdmin");
            for (Utilisateur us : listUtilisateur)
                model.addRow(new String[]{us.getIduser()+"",us.getLogin(),us.getPassword(),us.getNom(),us.getPrenom(),us.getDatenaiss()+"",us.getGenre(),us.getIdadmin()+""});
            table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JframeHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemListeUserActionPerformed

    private void MenuItemListeCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListeCompteActionPerformed
        try {
            // TODO add your handling code here:
            List<Compte> listCompte = controlleur.routeVersListAllCompte();
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Id");
            model.addColumn("Solde");
            model.addColumn("user");
            for (Compte ad : listCompte)
                model.addRow(new Object[]{ad.getIdcompte()+"",ad.getSolde(),ad.getIduser()});
            table.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(JframeHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemListeCompteActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int numeroLigne = table.getSelectedRow();
        TableModel model = table.getModel();
        
        if(quelMenu.equals("admin")){
            try {
                String id = model.getValueAt(numeroLigne, 0).toString();
                int idadmin = Integer.parseInt(id);
                
                JframeSaveAdmin jFrameAdmin =
                        new JframeSaveAdmin("Update", idadmin, this);
                jFrameAdmin.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(JframeHome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(quelMenu.equals("User")){
            
            String id = model.getValueAt(numeroLigne, 0).toString();
                int iduser = Integer.parseInt(id);
                
                Jframesaveutilisateur jFrameUtilisateur =
                        new Jframesaveutilisateur("Update", iduser, this);
                jFrameUtilisateur.setVisible(true);
           }
    }//GEN-LAST:event_tableMouseClicked

    private void MenuItemCreerAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerAdminActionPerformed
        try {
            // TODO add your handling code here:
            new JframeSaveAdmin("add", 0, this).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(JframeHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemCreerAdminActionPerformed

    private void MenuItemCreerUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerUserActionPerformed
        // TODO add your handling code here:
        new Jframesaveutilisateur("Add", 0, this).setVisible(true);
        
    }//GEN-LAST:event_MenuItemCreerUserActionPerformed

    private void MenuItemCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerCompteActionPerformed
        new Jframesavecompte().setVisible(true);
    }//GEN-LAST:event_MenuItemCreerCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeHome("admin").setVisible(true);
            }
        });
    }

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemCreerAdmin;
    private javax.swing.JMenuItem MenuItemCreerCompte;
    private javax.swing.JMenuItem MenuItemCreerUser;
    private javax.swing.JMenuItem MenuItemListeAdmin;
    private javax.swing.JMenuItem MenuItemListeCompte;
    private javax.swing.JMenuItem MenuItemListeUser;
    private javax.swing.JMenu MenuUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
